### ISSUE TITLE
方法可以实现mixin吗，这里？

### ISSUE THREAD

**Issue by yanlee26** [echo008/mp-mixin#1]

**Comment by yanlee26** [comment]
`  function merge(mixins, options) {
    mixins.reverse().forEach(mixin => {
      if (Object.prototype.toString.call(mixin).slice(8, -1) === 'Object') {
        for (let [key, value] of Object.entries(mixin)) {
          if (key === 'data') {
            options.data = Object.assign({}, value, options.data)
          } else {
            let native = options[key]
            options[key] = function (...args) {
              value.call(this, ...args) // 先执行mixins里lifecycle及method
              return native && native.call(this, ...args)
            }
          }
        }
      }
    })
  }` 这样改写merge方法，可生效

**Comment by echo008** [comment]
> `function merge(mixins, options) { mixins.reverse().forEach(mixin => { if (Object.prototype.toString.call(mixin).slice(8, -1) === 'Object') { for (let [key, value] of Object.entries(mixin)) { if (key === 'data') { options.data = Object.assign({}, value, options.data) } else { let native = options[key] options[key] = function (...args) { value.call(this, ...args) // 先执行mixins里lifecycle及method return native && native.call(this, ...args) } } } } }) }` 这样改写merge方法，可生效

非常感谢提出优化的建议，这个主要考虑如果是一个额外非函数的，比如Page({data: {}, props: {}}),这样的形式出现。

**Comment by yanlee26** [comment]
不谢，如果能再扩展下它的filter，watcher，computed属性就更完美了😄

**Comment by echo008** [comment]
> 不谢，如果能再扩展下它的filter，watcher，computed属性就更完美了😄

filter可以考虑用wxs函数，watcher,computed有考虑实现，最近工作上有些繁忙，估计得延后下。也考虑用gulp做个编译工具，不知道有没有好的思路之类

**Comment by yanlee26** [comment]
彼此彼此，搞个npm包，命令行初始化一下小程序项目，然后像ng那样都用命令新建模块。 最近业务搞的都没兴趣搞有意思的事情了。。。

**Comment by echo008** [comment]
> 彼此彼此，搞个npm包，命令行初始化一下小程序项目，然后像ng那样都用命令新建模块。 最近业务搞的都没兴趣搞有意思的事情了。。。

嗯嗯，这个考虑下，我最近工作也较忙，也没什么空做些尝试的事了

**Comment by yanlee26** [comment]
goood dude！！
